import 'package:myrandomlibrary/discovery/model/theme_concept.dart';

/// Curated concept catalog used by theme discovery. Pure data — no logic.
const List<ThemeConcept> kThemeConcepts = [
  // ── Seasonal & Holiday ───────────────────────────────────────────────────
  ThemeConcept(
    id: 'halloween',
    displayName: 'Halloween',
    displayNameEs: 'Halloween',
    emoji: '🎃',
    category: 'seasonal',
    keywords: [
      'halloween',
      'spooky',
      'haunted',
      'haunting',
      'trick or treat',
      'october',
    ],
    keywordsEs: [
      'noche de brujas',
      'embrujado',
      'embrujada',
      'encantada',
      'escalofriante',
      'espeluznante',
      'truco o trato',
      'octubre',
    ],
    relatedConceptIds: [
      'witches',
      'vampires',
      'ghosts',
      'werewolves',
      'supernatural',
      'horror',
      'occult',
      'dark_fantasy',
      'autumn',
    ],
  ),
  ThemeConcept(
    id: 'christmas',
    displayName: 'Christmas',
    displayNameEs: 'Navidad',
    emoji: '🎄',
    category: 'seasonal',
    keywords: [
      'christmas',
      'xmas',
      'santa',
      'christmas eve',
      'christmas day',
      'holiday',
      'festive',
      'advent',
    ],
    keywordsEs: [
      'navidad',
      'navideno',
      'navidena',
      'nochebuena',
      'papa noel',
      'reyes magos',
      'fiestas navidenas',
      'adviento',
    ],
    relatedConceptIds: ['winter', 'romance', 'family', 'cozy'],
  ),
  ThemeConcept(
    id: 'autumn',
    displayName: 'Autumn',
    displayNameEs: 'Otoño',
    emoji: '🍂',
    category: 'seasonal',
    keywords: [
      'autumn',
      'fall',
      'october',
      'november',
      'harvest',
      'leaves',
      'foliage',
    ],
    keywordsEs: ['otono', 'otonal', 'octubre', 'noviembre', 'cosecha', 'hojas'],
    relatedConceptIds: ['halloween', 'cozy', 'nature', 'small_town'],
  ),
  ThemeConcept(
    id: 'winter',
    displayName: 'Winter',
    displayNameEs: 'Invierno',
    emoji: '❄️',
    category: 'seasonal',
    keywords: ['winter', 'snow', 'snowy', 'blizzard', 'frost', 'ice', 'frozen'],
    keywordsEs: [
      'invierno',
      'invernal',
      'nieve',
      'nevado',
      'ventisca',
      'escarcha',
      'hielo',
      'helado',
    ],
    relatedConceptIds: ['christmas', 'cozy', 'survival', 'nature'],
  ),
  ThemeConcept(
    id: 'summer',
    displayName: 'Summer',
    displayNameEs: 'Verano',
    emoji: '☀️',
    category: 'seasonal',
    keywords: [
      'summer',
      'beach',
      'seaside',
      'vacation',
      'holiday',
      'summer break',
    ],
    keywordsEs: [
      'verano',
      'veraniego',
      'playa',
      'costa',
      'vacaciones',
      'vacaciones de verano',
    ],
    relatedConceptIds: ['romance', 'travel', 'coming_of_age', 'friendship'],
  ),
  ThemeConcept(
    id: 'spring',
    displayName: 'Spring',
    displayNameEs: 'Primavera',
    emoji: '🌸',
    category: 'seasonal',
    keywords: ['spring', 'blossom', 'flowers', 'easter', 'garden'],
    keywordsEs: ['primavera', 'primaveral', 'flores', 'pascua', 'jardin'],
    relatedConceptIds: ['nature', 'romance', 'cozy'],
  ),

  // ── Supernatural & Paranormal ────────────────────────────────────────────
  ThemeConcept(
    id: 'witches',
    displayName: 'Witches',
    displayNameEs: 'Brujas',
    emoji: '🧙',
    category: 'supernatural',
    keywords: [
      'witch',
      'witches',
      'witchcraft',
      'coven',
      'spell',
      'spells',
      'sorcery',
    ],
    keywordsEs: [
      'bruja',
      'brujo',
      'brujeria',
      'aquelarre',
      'hechizo',
      'hechicera',
      'hechiceria',
    ],
    relatedConceptIds: [
      'magic',
      'occult',
      'supernatural',
      'dark_fantasy',
      'halloween',
      'fantasy',
    ],
  ),
  ThemeConcept(
    id: 'vampires',
    displayName: 'Vampires',
    displayNameEs: 'Vampiros',
    emoji: '🧛',
    category: 'supernatural',
    keywords: [
      'vampire',
      'vampires',
      'vampire hunter',
      'bloodsucker',
      'immortal',
    ],
    keywordsEs: [
      'vampiro',
      'vampira',
      'cazador de vampiros',
      'chupasangre',
      'inmortal',
    ],
    relatedConceptIds: [
      'supernatural',
      'horror',
      'dark_fantasy',
      'romance',
      'halloween',
    ],
  ),
  ThemeConcept(
    id: 'werewolves',
    displayName: 'Werewolves',
    displayNameEs: 'Hombres lobo',
    emoji: '🐺',
    category: 'supernatural',
    keywords: [
      'werewolf',
      'werewolves',
      'lycanthrope',
      'lycanthropy',
      'wolf shifter',
      'shapeshifter',
    ],
    keywordsEs: [
      'hombre lobo',
      'hombres lobo',
      'licantropo',
      'licantropia',
      'cambiaformas',
    ],
    relatedConceptIds: [
      'supernatural',
      'fantasy',
      'horror',
      'romance',
      'halloween',
    ],
  ),
  ThemeConcept(
    id: 'ghosts',
    displayName: 'Ghosts',
    displayNameEs: 'Fantasmas',
    emoji: '👻',
    category: 'supernatural',
    keywords: [
      'ghost',
      'ghosts',
      'spirit',
      'spirits',
      'apparition',
      'haunted',
      'haunting',
      'afterlife',
    ],
    keywordsEs: [
      'fantasma',
      'espiritu',
      'espectro',
      'aparicion',
      'embrujado',
      'encantada',
      'mas alla',
    ],
    relatedConceptIds: ['supernatural', 'horror', 'paranormal', 'halloween'],
  ),
  ThemeConcept(
    id: 'demons',
    displayName: 'Demons',
    displayNameEs: 'Demonios',
    emoji: '😈',
    category: 'supernatural',
    keywords: [
      'demon',
      'demons',
      'demonic',
      'hell',
      'possession',
      'possessed',
      'exorcism',
    ],
    keywordsEs: [
      'demonio',
      'demoniaco',
      'infierno',
      'posesion',
      'poseido',
      'poseida',
      'exorcismo',
    ],
    relatedConceptIds: ['supernatural', 'horror', 'occult'],
  ),
  ThemeConcept(
    id: 'angels',
    displayName: 'Angels',
    displayNameEs: 'Ángeles',
    emoji: '👼',
    category: 'supernatural',
    keywords: ['angel', 'angels', 'fallen angel', 'archangel', 'celestial'],
    keywordsEs: ['angel', 'angeles', 'angel caido', 'arcangel', 'celestial'],
    relatedConceptIds: ['supernatural', 'fantasy', 'mythology'],
  ),
  ThemeConcept(
    id: 'supernatural',
    displayName: 'Supernatural',
    displayNameEs: 'Sobrenatural',
    emoji: '🔮',
    category: 'supernatural',
    keywords: [
      'supernatural',
      'paranormal',
      'otherworldly',
      'unexplained',
      'psychic',
      'telepathic',
    ],
    keywordsEs: [
      'sobrenatural',
      'paranormal',
      'inexplicable',
      'psiquico',
      'telepatia',
      'telepatico',
    ],
    relatedConceptIds: ['ghosts', 'vampires', 'witches', 'demons', 'magic'],
  ),

  // ── Fantasy & Magic ──────────────────────────────────────────────────────
  ThemeConcept(
    id: 'fantasy',
    displayName: 'Fantasy',
    displayNameEs: 'Fantasía',
    emoji: '🏰',
    category: 'fantasy',
    keywords: ['fantasy', 'magical', 'enchanted', 'mythical', 'fantastical'],
    keywordsEs: ['fantasia', 'fantastico', 'fantastica', 'magico', 'mitico'],
    relatedConceptIds: [
      'magic',
      'epic_fantasy',
      'urban_fantasy',
      'dark_fantasy',
      'mythology',
    ],
  ),
  ThemeConcept(
    id: 'epic_fantasy',
    displayName: 'Epic Fantasy',
    displayNameEs: 'Fantasía épica',
    emoji: '⚔️',
    category: 'fantasy',
    keywords: [
      'epic fantasy',
      'kingdom',
      'kingdoms',
      'throne',
      'empire',
      'prophecy',
      'quest',
      'war',
      'chosen one',
    ],
    keywordsEs: [
      'fantasia epica',
      'alta fantasia',
      'reino',
      'trono',
      'imperio',
      'profecia',
      'elegido',
      'elegida',
    ],
    relatedConceptIds: ['fantasy', 'political_intrigue', 'magic', 'mythology'],
  ),
  ThemeConcept(
    id: 'urban_fantasy',
    displayName: 'Urban Fantasy',
    displayNameEs: 'Fantasía urbana',
    emoji: '🌃',
    category: 'fantasy',
    keywords: [
      'urban fantasy',
      'modern magic',
      'magical city',
      'supernatural city',
      'hidden world',
    ],
    keywordsEs: [
      'fantasia urbana',
      'magia moderna',
      'ciudad magica',
      'mundo oculto',
    ],
    relatedConceptIds: [
      'fantasy',
      'supernatural',
      'witches',
      'vampires',
      'magic',
    ],
  ),
  ThemeConcept(
    id: 'magic',
    displayName: 'Magic',
    displayNameEs: 'Magia',
    emoji: '✨',
    category: 'fantasy',
    keywords: [
      'magic',
      'magical',
      'spell',
      'spells',
      'sorcery',
      'wizard',
      'wizardry',
      'enchantment',
      'enchanted',
    ],
    keywordsEs: [
      'magia',
      'magico',
      'magica',
      'hechizo',
      'mago',
      'hechicero',
      'encantamiento',
    ],
    relatedConceptIds: ['witches', 'fantasy', 'dark_fantasy', 'supernatural'],
  ),
  ThemeConcept(
    id: 'dragons',
    displayName: 'Dragons',
    displayNameEs: 'Dragones',
    emoji: '🐉',
    category: 'fantasy',
    keywords: ['dragon', 'dragons', 'dragon rider', 'dragonrider'],
    keywordsEs: [
      'dragon',
      'dragones',
      'jinete de dragones',
      'jinete de dragon',
    ],
    relatedConceptIds: ['fantasy', 'epic_fantasy', 'magic', 'mythology'],
  ),
  ThemeConcept(
    id: 'fae',
    displayName: 'Fae',
    displayNameEs: 'Hadas',
    emoji: '🧚',
    category: 'fantasy',
    keywords: [
      'fae',
      'faerie',
      'fairies',
      'fairy',
      'fae realm',
      'faerie realm',
      'fae court',
    ],
    keywordsEs: [
      'hada',
      'hadas',
      'feerico',
      'corte feerica',
      'reino de las hadas',
    ],
    relatedConceptIds: ['fantasy', 'magic', 'romance', 'mythology'],
  ),

  // ── Romance ──────────────────────────────────────────────────────────────
  ThemeConcept(
    id: 'romance',
    displayName: 'Romance',
    displayNameEs: 'Romance',
    emoji: '💕',
    category: 'romance',
    keywords: [
      'romance',
      'romantic',
      'love story',
      'love interest',
      'relationship',
      'lovers',
    ],
    keywordsEs: [
      'romantica',
      'romantico',
      'novela romantica',
      'historia de amor',
      'amantes',
      'enamorados',
    ],
    relatedConceptIds: [
      'contemporary_romance',
      'romantic_comedy',
      'fantasy_romance',
      'dark_romance',
      'enemies_to_lovers',
    ],
  ),
  ThemeConcept(
    id: 'romantic_comedy',
    displayName: 'Romantic Comedy',
    displayNameEs: 'Comedia romántica',
    emoji: '😄',
    category: 'romance',
    keywords: ['romantic comedy', 'funny romance', 'comedy romance'],
    keywordsEs: ['comedia romantica', 'romance divertido'],
    aliases: ['romcom', 'rom-com'],
    relatedConceptIds: [
      'romance',
      'contemporary',
      'workplace',
      'friends_to_lovers',
    ],
  ),
  ThemeConcept(
    id: 'dark_romance',
    displayName: 'Dark Romance',
    displayNameEs: 'Romance oscuro',
    emoji: '🖤',
    category: 'romance',
    keywords: [
      'dark romance',
      'forbidden romance',
      'obsession',
      'possessive',
      'morally grey',
    ],
    keywordsEs: [
      'romance oscuro',
      'romance prohibido',
      'amor prohibido',
      'obsesion',
      'posesivo',
    ],
    relatedConceptIds: ['romance', 'gothic', 'psychological', 'thriller'],
  ),
  ThemeConcept(
    id: 'fantasy_romance',
    displayName: 'Fantasy Romance',
    displayNameEs: 'Romantasy',
    emoji: '💘',
    category: 'romance',
    keywords: ['fantasy romance', 'romantasy', 'magical romance'],
    keywordsEs: ['romance fantastico', 'fantasia romantica', 'romance magico'],
    relatedConceptIds: ['fantasy', 'romance', 'magic', 'fae', 'witches'],
  ),
  ThemeConcept(
    id: 'enemies_to_lovers',
    displayName: 'Enemies to Lovers',
    displayNameEs: 'De enemigos a amantes',
    emoji: '⚡',
    category: 'romance',
    keywords: [
      'enemies to lovers',
      'enemies-to-lovers',
      'rivals to lovers',
      'hate to love',
    ],
    keywordsEs: [
      'enemigos a amantes',
      'de enemigos a amantes',
      'rivales a amantes',
      'del odio al amor',
    ],
    relatedConceptIds: ['romance', 'romantic_comedy', 'fantasy_romance'],
  ),
  ThemeConcept(
    id: 'friends_to_lovers',
    displayName: 'Friends to Lovers',
    displayNameEs: 'De amigos a amantes',
    emoji: '🤝',
    category: 'romance',
    keywords: [
      'friends to lovers',
      'friends-to-lovers',
      'childhood friends',
      'best friends romance',
    ],
    keywordsEs: [
      'amigos a amantes',
      'de amigos a amantes',
      'amigos de la infancia',
    ],
    relatedConceptIds: ['romance', 'contemporary_romance'],
  ),

  // ── Mystery & Thriller ───────────────────────────────────────────────────
  ThemeConcept(
    id: 'mystery',
    displayName: 'Mystery',
    displayNameEs: 'Misterio',
    emoji: '🔍',
    category: 'mystery',
    keywords: [
      'mystery',
      'detective',
      'investigation',
      'murder mystery',
      'whodunit',
      'clues',
      'suspect',
    ],
    keywordsEs: [
      'misterio',
      'detective',
      'investigacion',
      'pistas',
      'sospechoso',
      'enigma',
    ],
    relatedConceptIds: [
      'crime',
      'thriller',
      'psychological_thriller',
      'detective',
    ],
  ),
  ThemeConcept(
    id: 'thriller',
    displayName: 'Thriller',
    displayNameEs: 'Thriller',
    emoji: '🔪',
    category: 'mystery',
    keywords: [
      'thriller',
      'suspense',
      'danger',
      'conspiracy',
      'chase',
      'hostage',
    ],
    keywordsEs: ['suspense', 'peligro', 'conspiracion', 'persecucion', 'rehen'],
    relatedConceptIds: ['mystery', 'crime', 'psychological_thriller', 'action'],
  ),
  ThemeConcept(
    id: 'psychological_thriller',
    displayName: 'Psychological Thriller',
    displayNameEs: 'Thriller psicológico',
    emoji: '🧠',
    category: 'mystery',
    keywords: [
      'psychological thriller',
      'unreliable narrator',
      'paranoia',
      'manipulation',
      'obsession',
      'mind games',
    ],
    keywordsEs: [
      'thriller psicologico',
      'narrador poco fiable',
      'paranoia',
      'manipulacion',
      'obsesion',
    ],
    relatedConceptIds: ['thriller', 'mystery', 'psychological_horror'],
  ),
  ThemeConcept(
    id: 'crime',
    displayName: 'Crime',
    displayNameEs: 'Crimen',
    emoji: '🚔',
    category: 'mystery',
    keywords: [
      'crime',
      'criminal',
      'murder',
      'killer',
      'police',
      'detective',
      'investigation',
      'mafia',
    ],
    keywordsEs: [
      'crimen',
      'criminal',
      'asesinato',
      'asesino',
      'policia',
      'policiaca',
      'mafia',
    ],
    relatedConceptIds: ['mystery', 'thriller', 'suspense'],
  ),
  ThemeConcept(
    id: 'serial_killer',
    displayName: 'Serial Killer',
    displayNameEs: 'Asesino en serie',
    emoji: '🩸',
    category: 'mystery',
    keywords: [
      'serial killer',
      'serial murderer',
      'killer',
      'murders',
      'profiler',
    ],
    keywordsEs: ['asesino en serie', 'asesinatos', 'perfilador', 'perfiladora'],
    relatedConceptIds: ['crime', 'thriller', 'psychological_thriller'],
  ),

  // ── Science Fiction ──────────────────────────────────────────────────────
  ThemeConcept(
    id: 'science_fiction',
    displayName: 'Science Fiction',
    displayNameEs: 'Ciencia ficción',
    emoji: '🚀',
    category: 'science_fiction',
    keywords: [
      'science fiction',
      'sci-fi',
      'futuristic',
      'future',
      'advanced technology',
    ],
    keywordsEs: [
      'ciencia ficcion',
      'futurista',
      'futuro',
      'tecnologia avanzada',
    ],
    aliases: ['scifi', 'sf'],
    relatedConceptIds: [
      'space',
      'dystopian',
      'cyberpunk',
      'artificial_intelligence',
    ],
  ),
  ThemeConcept(
    id: 'space',
    displayName: 'Space',
    displayNameEs: 'Espacio',
    emoji: '🪐',
    category: 'science_fiction',
    keywords: [
      'space',
      'spaceship',
      'spacecraft',
      'galaxy',
      'planet',
      'astronaut',
      'interstellar',
    ],
    keywordsEs: [
      'espacio',
      'nave espacial',
      'galaxia',
      'planeta',
      'astronauta',
      'interestelar',
    ],
    relatedConceptIds: ['science_fiction', 'space_opera', 'aliens'],
  ),
  ThemeConcept(
    id: 'aliens',
    displayName: 'Aliens',
    displayNameEs: 'Alienígenas',
    emoji: '👽',
    category: 'science_fiction',
    keywords: ['alien', 'aliens', 'extraterrestrial', 'first contact'],
    keywordsEs: ['alienigena', 'extraterrestre', 'primer contacto'],
    relatedConceptIds: ['science_fiction', 'space', 'space_opera'],
  ),
  ThemeConcept(
    id: 'dystopian',
    displayName: 'Dystopian',
    displayNameEs: 'Distopía',
    emoji: '🏙️',
    category: 'science_fiction',
    keywords: [
      'dystopian',
      'dystopia',
      'authoritarian',
      'oppressive regime',
      'totalitarian',
      'surveillance',
    ],
    keywordsEs: [
      'distopia',
      'distopico',
      'distopica',
      'autoritario',
      'regimen opresivo',
      'totalitario',
      'vigilancia',
    ],
    relatedConceptIds: [
      'science_fiction',
      'post_apocalyptic',
      'political_intrigue',
    ],
  ),
  ThemeConcept(
    id: 'post_apocalyptic',
    displayName: 'Post-Apocalyptic',
    displayNameEs: 'Postapocalíptico',
    emoji: '☢️',
    category: 'science_fiction',
    keywords: [
      'post-apocalyptic',
      'apocalypse',
      'wasteland',
      'survival',
      'disaster',
      'end of the world',
    ],
    keywordsEs: [
      'postapocaliptico',
      'postapocaliptica',
      'apocalipsis',
      'yermo',
      'fin del mundo',
    ],
    aliases: ['postapocalyptic'],
    relatedConceptIds: ['dystopian', 'survival', 'science_fiction'],
  ),
  ThemeConcept(
    id: 'cyberpunk',
    displayName: 'Cyberpunk',
    displayNameEs: 'Cyberpunk',
    emoji: '🤖',
    category: 'science_fiction',
    keywords: [
      'cyberpunk',
      'cybernetic',
      'megacorporation',
      'hacker',
      'neon city',
    ],
    keywordsEs: [
      'ciberpunk',
      'cibernetico',
      'megacorporacion',
      'ciudad de neon',
    ],
    relatedConceptIds: ['science_fiction', 'technology', 'dystopian'],
  ),

  // ── Historical & Period ──────────────────────────────────────────────────
  ThemeConcept(
    id: 'historical',
    displayName: 'Historical',
    displayNameEs: 'Histórica',
    emoji: '📜',
    category: 'historical',
    keywords: [
      'historical',
      'historical fiction',
      'period',
      'historical novel',
    ],
    keywordsEs: [
      'historica',
      'historico',
      'novela historica',
      'ficcion historica',
      'epoca',
    ],
    relatedConceptIds: ['historical_romance', 'war', 'politics'],
  ),
  ThemeConcept(
    id: 'historical_romance',
    displayName: 'Historical Romance',
    displayNameEs: 'Romance histórico',
    emoji: '👒',
    category: 'historical',
    keywords: [
      'historical romance',
      'regency',
      'victorian',
      'duke',
      'duchess',
      'lord',
      'lady',
    ],
    keywordsEs: [
      'romance historico',
      'regencia',
      'victoriana',
      'duque',
      'duquesa',
    ],
    relatedConceptIds: ['romance', 'historical'],
  ),
  ThemeConcept(
    id: 'medieval',
    displayName: 'Medieval',
    displayNameEs: 'Medieval',
    emoji: '🛡️',
    category: 'historical',
    keywords: [
      'medieval',
      'middle ages',
      'knight',
      'castle',
      'kingdom',
      'feudal',
    ],
    keywordsEs: ['edad media', 'caballero', 'castillo', 'reino', 'feudal'],
    relatedConceptIds: ['historical', 'fantasy', 'epic_fantasy'],
  ),
  ThemeConcept(
    id: 'victorian',
    displayName: 'Victorian',
    displayNameEs: 'Victoriana',
    emoji: '🎩',
    category: 'historical',
    keywords: ['victorian', 'victorian era', 'london', '19th century'],
    keywordsEs: [
      'victoriana',
      'victoriano',
      'epoca victoriana',
      'londres',
      'siglo xix',
    ],
    relatedConceptIds: ['historical', 'gothic', 'mystery', 'romance'],
  ),

  // ── Adventure & Action ───────────────────────────────────────────────────
  ThemeConcept(
    id: 'adventure',
    displayName: 'Adventure',
    displayNameEs: 'Aventura',
    emoji: '🧭',
    category: 'adventure',
    keywords: [
      'adventure',
      'quest',
      'expedition',
      'journey',
      'exploration',
      'treasure',
    ],
    keywordsEs: [
      'aventura',
      'aventuras',
      'expedicion',
      'viaje',
      'exploracion',
      'tesoro',
      'busqueda',
    ],
    relatedConceptIds: ['fantasy', 'travel', 'action'],
  ),
  ThemeConcept(
    id: 'action',
    displayName: 'Action',
    displayNameEs: 'Acción',
    emoji: '💥',
    category: 'adventure',
    keywords: ['action', 'combat', 'battle', 'fight', 'warrior', 'mercenary'],
    keywordsEs: [
      'accion',
      'combate',
      'batalla',
      'lucha',
      'guerrero',
      'mercenario',
    ],
    relatedConceptIds: ['adventure', 'thriller', 'war'],
  ),
  ThemeConcept(
    id: 'survival',
    displayName: 'Survival',
    displayNameEs: 'Supervivencia',
    emoji: '🏕️',
    category: 'adventure',
    keywords: [
      'survival',
      'survive',
      'stranded',
      'wilderness',
      'disaster',
      'scarce resources',
    ],
    keywordsEs: [
      'supervivencia',
      'sobrevivir',
      'naufrago',
      'varado',
      'desastre',
    ],
    relatedConceptIds: ['post_apocalyptic', 'thriller', 'adventure'],
  ),
  ThemeConcept(
    id: 'pirates',
    displayName: 'Pirates',
    displayNameEs: 'Piratas',
    emoji: '🏴‍☠️',
    category: 'adventure',
    keywords: ['pirate', 'pirates', 'piracy', 'pirate ship', 'treasure'],
    keywordsEs: ['pirata', 'piratas', 'pirateria', 'barco pirata', 'tesoro'],
    relatedConceptIds: ['adventure', 'historical', 'fantasy'],
  ),

  // ── Cozy & Atmosphere ────────────────────────────────────────────────────
  ThemeConcept(
    id: 'cozy',
    displayName: 'Cozy',
    displayNameEs: 'Acogedor',
    emoji: '☕',
    category: 'atmosphere',
    keywords: [
      'cozy',
      'cosy',
      'comforting',
      'heartwarming',
      'wholesome',
      'feel-good',
    ],
    keywordsEs: [
      'acogedor',
      'acogedora',
      'reconfortante',
      'entranable',
      'tierno',
    ],
    relatedConceptIds: [
      'small_town',
      'romance',
      'autumn',
      'winter',
      'found_family',
    ],
    negativeKeywords: ['gore', 'grimdark', 'brutal', 'visceral'],
  ),
  ThemeConcept(
    id: 'small_town',
    displayName: 'Small Town',
    displayNameEs: 'Pueblo pequeño',
    emoji: '🏡',
    category: 'atmosphere',
    keywords: ['small town', 'village', 'hometown', 'countryside', 'community'],
    keywordsEs: [
      'pueblo',
      'pueblo pequeno',
      'aldea',
      'villa',
      'campo',
      'comunidad',
    ],
    relatedConceptIds: ['cozy', 'romance', 'contemporary'],
  ),
  ThemeConcept(
    id: 'found_family',
    displayName: 'Found Family',
    displayNameEs: 'Familia elegida',
    emoji: '🫂',
    category: 'atmosphere',
    keywords: [
      'found family',
      'chosen family',
      'found-family',
      'unlikely family',
    ],
    keywordsEs: [
      'familia elegida',
      'familia encontrada',
      'familia improvisada',
    ],
    relatedConceptIds: ['fantasy', 'cozy', 'friendship', 'adventure'],
  ),
  ThemeConcept(
    id: 'dark_academia',
    displayName: 'Dark Academia',
    displayNameEs: 'Dark Academia',
    emoji: '🎓',
    category: 'atmosphere',
    keywords: [
      'dark academia',
      'academia',
      'university',
      'college',
      'secret society',
      'classical literature',
      'boarding school',
    ],
    keywordsEs: [
      'academia oscura',
      'universidad',
      'sociedad secreta',
      'internado',
      'literatura clasica',
    ],
    relatedConceptIds: ['mystery', 'gothic', 'dark', 'historical'],
  ),

  // ── Social & Character Themes ────────────────────────────────────────────
  ThemeConcept(
    id: 'friendship',
    displayName: 'Friendship',
    displayNameEs: 'Amistad',
    emoji: '🤗',
    category: 'social',
    keywords: ['friendship', 'friends', 'best friends', 'companionship'],
    keywordsEs: [
      'amistad',
      'amigos',
      'amigas',
      'mejores amigos',
      'companerismo',
    ],
    relatedConceptIds: ['found_family', 'coming_of_age', 'contemporary'],
  ),
  ThemeConcept(
    id: 'coming_of_age',
    displayName: 'Coming of Age',
    displayNameEs: 'Crecimiento personal',
    emoji: '🌱',
    category: 'social',
    keywords: [
      'coming of age',
      'growing up',
      'adolescence',
      'teenage',
      'young adult',
    ],
    keywordsEs: [
      'crecer',
      'madurez',
      'adolescencia',
      'adolescente',
      'juvenil',
      'novela de iniciacion',
    ],
    aliases: ['ya'],
    relatedConceptIds: ['friendship', 'romance', 'contemporary'],
  ),
  ThemeConcept(
    id: 'family',
    displayName: 'Family',
    displayNameEs: 'Familia',
    emoji: '👨‍👩‍👧',
    category: 'social',
    keywords: [
      'family',
      'siblings',
      'sister',
      'brother',
      'mother',
      'father',
      'parents',
      'daughter',
    ],
    keywordsEs: [
      'familia',
      'hermanos',
      'hermana',
      'hermano',
      'madre',
      'padre',
      'padres',
      'hija',
      'hijo',
    ],
    relatedConceptIds: ['found_family', 'relationships', 'cozy'],
  ),
  ThemeConcept(
    id: 'political_intrigue',
    displayName: 'Political Intrigue',
    displayNameEs: 'Intriga política',
    emoji: '👑',
    category: 'social',
    keywords: [
      'political intrigue',
      'court politics',
      'political',
      'conspiracy',
      'succession',
      'throne',
      'diplomacy',
      'power struggle',
    ],
    keywordsEs: [
      'intriga politica',
      'intrigas palaciegas',
      'conspiracion',
      'sucesion',
      'trono',
      'diplomacia',
      'lucha de poder',
    ],
    relatedConceptIds: ['epic_fantasy', 'historical', 'war', 'royalty'],
  ),
  ThemeConcept(
    id: 'war',
    displayName: 'War',
    displayNameEs: 'Guerra',
    emoji: '🪖',
    category: 'social',
    keywords: [
      'war',
      'warfare',
      'battle',
      'soldier',
      'army',
      'military',
      'conflict',
    ],
    keywordsEs: [
      'guerra',
      'belico',
      'batalla',
      'soldado',
      'ejercito',
      'militar',
      'conflicto',
    ],
    relatedConceptIds: [
      'historical',
      'political_intrigue',
      'epic_fantasy',
      'survival',
    ],
  ),

  // ── Mythology ────────────────────────────────────────────────────────────
  ThemeConcept(
    id: 'mythology',
    displayName: 'Mythology',
    displayNameEs: 'Mitología',
    emoji: '🏛️',
    category: 'mythology',
    keywords: ['mythology', 'myth', 'mythical', 'gods', 'goddess', 'pantheon'],
    keywordsEs: ['mitologia', 'mito', 'mitico', 'dioses', 'diosa', 'panteon'],
    relatedConceptIds: ['fantasy', 'ancient_world', 'magic'],
  ),
  ThemeConcept(
    id: 'greek_mythology',
    displayName: 'Greek Mythology',
    displayNameEs: 'Mitología griega',
    emoji: '⚡',
    category: 'mythology',
    keywords: [
      'greek mythology',
      'greek gods',
      'olympians',
      'zeus',
      'hades',
      'athena',
      'poseidon',
    ],
    keywordsEs: [
      'mitologia griega',
      'dioses griegos',
      'olimpo',
      'olimpicos',
      'atenea',
      'poseidon',
    ],
    relatedConceptIds: ['mythology', 'fantasy', 'ancient_world'],
  ),
  ThemeConcept(
    id: 'norse_mythology',
    displayName: 'Norse Mythology',
    displayNameEs: 'Mitología nórdica',
    emoji: '🔨',
    category: 'mythology',
    keywords: [
      'norse mythology',
      'norse gods',
      'odin',
      'thor',
      'loki',
      'valhalla',
      'asgard',
    ],
    keywordsEs: [
      'mitologia nordica',
      'dioses nordicos',
      'odin',
      'valhalla',
      'asgard',
    ],
    relatedConceptIds: ['mythology', 'fantasy', 'vikings'],
  ),

  // ── Additional concepts referenced by related lists ──────────────────────
  ThemeConcept(
    id: 'horror',
    displayName: 'Horror',
    displayNameEs: 'Terror',
    emoji: '😱',
    category: 'horror',
    keywords: ['horror', 'terror', 'scary', 'frightening', 'gore', 'nightmare'],
    keywordsEs: ['terror', 'miedo', 'aterrador', 'terrorifico', 'pesadilla'],
    relatedConceptIds: [
      'supernatural',
      'ghosts',
      'demons',
      'psychological_horror',
      'halloween',
    ],
  ),
  ThemeConcept(
    id: 'occult',
    displayName: 'Occult',
    displayNameEs: 'Ocultismo',
    emoji: '🕯️',
    category: 'supernatural',
    keywords: ['occult', 'ritual', 'tarot', 'seance', 'grimoire', 'dark arts'],
    keywordsEs: [
      'ocultismo',
      'oculto',
      'ritual',
      'tarot',
      'sesion de espiritismo',
      'grimorio',
      'artes oscuras',
    ],
    relatedConceptIds: ['witches', 'demons', 'supernatural', 'magic'],
  ),
  ThemeConcept(
    id: 'dark_fantasy',
    displayName: 'Dark Fantasy',
    displayNameEs: 'Fantasía oscura',
    emoji: '🗡️',
    category: 'fantasy',
    keywords: ['dark fantasy', 'grimdark', 'cursed', 'sinister', 'blood magic'],
    keywordsEs: [
      'fantasia oscura',
      'maldito',
      'maldita',
      'siniestro',
      'magia de sangre',
    ],
    relatedConceptIds: ['fantasy', 'horror', 'gothic', 'vampires'],
  ),
  ThemeConcept(
    id: 'gothic',
    displayName: 'Gothic',
    displayNameEs: 'Gótico',
    emoji: '🦇',
    category: 'atmosphere',
    keywords: [
      'gothic',
      'gothic novel',
      'manor',
      'crumbling mansion',
      'brooding',
      'macabre',
    ],
    keywordsEs: [
      'gotico',
      'gotica',
      'novela gotica',
      'mansion',
      'caseron',
      'macabro',
    ],
    relatedConceptIds: ['horror', 'victorian', 'dark_romance', 'mystery'],
  ),
  ThemeConcept(
    id: 'paranormal',
    displayName: 'Paranormal',
    displayNameEs: 'Paranormal',
    emoji: '🌙',
    category: 'supernatural',
    keywords: ['paranormal', 'paranormal romance', 'poltergeist'],
    keywordsEs: ['paranormal', 'romance paranormal', 'medium', 'poltergeist'],
    relatedConceptIds: ['supernatural', 'ghosts', 'vampires', 'werewolves'],
  ),
  ThemeConcept(
    id: 'contemporary',
    displayName: 'Contemporary',
    displayNameEs: 'Contemporánea',
    emoji: '🏙',
    category: 'contemporary',
    keywords: [
      'contemporary',
      'modern day',
      'present day',
      'realistic fiction',
    ],
    keywordsEs: [
      'contemporanea',
      'contemporaneo',
      'actualidad',
      'ficcion realista',
    ],
    relatedConceptIds: ['contemporary_romance', 'friendship', 'family'],
  ),
  ThemeConcept(
    id: 'contemporary_romance',
    displayName: 'Contemporary Romance',
    displayNameEs: 'Romance contemporáneo',
    emoji: '💌',
    category: 'romance',
    keywords: [
      'contemporary romance',
      'modern romance',
      'second chance',
      'fake dating',
    ],
    keywordsEs: [
      'romance contemporaneo',
      'romantica contemporanea',
      'segunda oportunidad',
      'relacion falsa',
    ],
    relatedConceptIds: ['romance', 'contemporary', 'romantic_comedy'],
  ),
  ThemeConcept(
    id: 'psychological_horror',
    displayName: 'Psychological Horror',
    displayNameEs: 'Terror psicológico',
    emoji: '🌀',
    category: 'horror',
    keywords: [
      'psychological horror',
      'madness',
      'insanity',
      'dread',
      'disturbing',
    ],
    keywordsEs: [
      'terror psicologico',
      'locura',
      'demencia',
      'inquietante',
      'perturbador',
    ],
    relatedConceptIds: ['horror', 'psychological_thriller', 'psychological'],
  ),
  ThemeConcept(
    id: 'psychological',
    displayName: 'Psychological',
    displayNameEs: 'Psicológico',
    emoji: '🧩',
    category: 'social',
    keywords: [
      'psychological',
      'psyche',
      'trauma',
      'mental health',
      'obsession',
    ],
    keywordsEs: [
      'psicologico',
      'psicologica',
      'psique',
      'trauma',
      'salud mental',
      'obsesion',
    ],
    relatedConceptIds: ['psychological_thriller', 'psychological_horror'],
  ),
  ThemeConcept(
    id: 'suspense',
    displayName: 'Suspense',
    displayNameEs: 'Suspense',
    emoji: '⏳',
    category: 'mystery',
    keywords: [
      'suspense',
      'suspenseful',
      'tension',
      'cliffhanger',
      'edge of your seat',
    ],
    keywordsEs: ['suspense', 'intriga', 'tension', 'en vilo'],
    relatedConceptIds: ['thriller', 'mystery'],
  ),
  ThemeConcept(
    id: 'detective',
    displayName: 'Detective',
    displayNameEs: 'Detectives',
    emoji: '🕵️',
    category: 'mystery',
    keywords: ['detective', 'private investigator', 'sleuth', 'inspector'],
    keywordsEs: [
      'detective',
      'investigador privado',
      'inspector',
      'inspectora',
      'novela policiaca',
    ],
    relatedConceptIds: ['mystery', 'crime'],
  ),
  ThemeConcept(
    id: 'travel',
    displayName: 'Travel',
    displayNameEs: 'Viajes',
    emoji: '✈️',
    category: 'adventure',
    keywords: [
      'travel',
      'road trip',
      'journey abroad',
      'backpacking',
      'wanderlust',
    ],
    keywordsEs: ['viajes', 'viajar', 'viaje por carretera', 'mochilero'],
    relatedConceptIds: ['adventure', 'summer'],
  ),
  ThemeConcept(
    id: 'nature',
    displayName: 'Nature',
    displayNameEs: 'Naturaleza',
    emoji: '🌲',
    category: 'atmosphere',
    keywords: [
      'nature',
      'forest',
      'wilderness',
      'mountains',
      'wildlife',
      'ocean',
    ],
    keywordsEs: [
      'naturaleza',
      'bosque',
      'montanas',
      'fauna',
      'oceano',
      'selva',
    ],
    relatedConceptIds: ['spring', 'autumn', 'survival'],
  ),
  ThemeConcept(
    id: 'technology',
    displayName: 'Technology',
    displayNameEs: 'Tecnología',
    emoji: '💻',
    category: 'science_fiction',
    keywords: [
      'technology',
      'tech',
      'robot',
      'robots',
      'virtual reality',
      'hacking',
    ],
    keywordsEs: ['tecnologia', 'robot', 'robots', 'realidad virtual', 'hackeo'],
    relatedConceptIds: [
      'science_fiction',
      'cyberpunk',
      'artificial_intelligence',
    ],
  ),
  ThemeConcept(
    id: 'artificial_intelligence',
    displayName: 'Artificial Intelligence',
    displayNameEs: 'Inteligencia artificial',
    emoji: '🦾',
    category: 'science_fiction',
    keywords: [
      'artificial intelligence',
      'android',
      'sentient machine',
      'robot',
    ],
    keywordsEs: ['inteligencia artificial', 'androide', 'maquina consciente'],
    aliases: ['ai', 'ia'],
    relatedConceptIds: ['science_fiction', 'technology'],
  ),
  ThemeConcept(
    id: 'space_opera',
    displayName: 'Space Opera',
    displayNameEs: 'Space opera',
    emoji: '🌌',
    category: 'science_fiction',
    keywords: [
      'space opera',
      'galactic empire',
      'starship',
      'fleet',
      'interstellar war',
    ],
    keywordsEs: [
      'opera espacial',
      'imperio galactico',
      'nave estelar',
      'flota',
      'guerra interestelar',
    ],
    relatedConceptIds: ['space', 'science_fiction', 'aliens'],
  ),
  ThemeConcept(
    id: 'vikings',
    displayName: 'Vikings',
    displayNameEs: 'Vikingos',
    emoji: '🛶',
    category: 'historical',
    keywords: ['viking', 'vikings', 'norsemen', 'longship', 'raid', 'jarl'],
    keywordsEs: ['vikingo', 'vikingos', 'nordicos', 'drakkar', 'saqueo'],
    relatedConceptIds: ['norse_mythology', 'historical', 'war'],
  ),
  ThemeConcept(
    id: 'ancient_world',
    displayName: 'Ancient World',
    displayNameEs: 'Mundo antiguo',
    emoji: '🏺',
    category: 'historical',
    keywords: [
      'ancient',
      'ancient greece',
      'ancient rome',
      'ancient egypt',
      'antiquity',
      'pharaoh',
    ],
    keywordsEs: [
      'antigua grecia',
      'antigua roma',
      'antiguo egipto',
      'antiguedad',
      'faraon',
    ],
    relatedConceptIds: ['mythology', 'historical'],
  ),
  ThemeConcept(
    id: 'royalty',
    displayName: 'Royalty',
    displayNameEs: 'Realeza',
    emoji: '💎',
    category: 'social',
    keywords: [
      'royalty',
      'royal',
      'prince',
      'princess',
      'queen',
      'king',
      'crown',
    ],
    keywordsEs: ['realeza', 'principe', 'princesa', 'reina', 'rey', 'corona'],
    relatedConceptIds: [
      'political_intrigue',
      'historical_romance',
      'epic_fantasy',
    ],
  ),
  ThemeConcept(
    id: 'relationships',
    displayName: 'Relationships',
    displayNameEs: 'Relaciones',
    emoji: '💞',
    category: 'social',
    keywords: [
      'relationship',
      'relationships',
      'marriage',
      'divorce',
      'love triangle',
    ],
    keywordsEs: ['relaciones', 'matrimonio', 'divorcio', 'triangulo amoroso'],
    relatedConceptIds: ['romance', 'family'],
  ),
  ThemeConcept(
    id: 'politics',
    displayName: 'Politics',
    displayNameEs: 'Política',
    emoji: '🗳️',
    category: 'social',
    keywords: ['politics', 'political', 'election', 'government', 'senator'],
    keywordsEs: ['politica', 'politico', 'elecciones', 'gobierno', 'senador'],
    relatedConceptIds: ['political_intrigue', 'dystopian'],
  ),
  ThemeConcept(
    id: 'workplace',
    displayName: 'Workplace',
    displayNameEs: 'Trabajo',
    emoji: '💼',
    category: 'social',
    keywords: ['workplace', 'office', 'coworkers', 'boss', 'colleague'],
    keywordsEs: ['oficina', 'companeros de trabajo', 'jefe', 'jefa', 'colega'],
    relatedConceptIds: ['romantic_comedy', 'contemporary'],
  ),
  ThemeConcept(
    id: 'dark',
    displayName: 'Dark',
    displayNameEs: 'Oscuro',
    emoji: '🌑',
    category: 'atmosphere',
    keywords: ['dark', 'bleak', 'grim', 'disturbing', 'twisted'],
    keywordsEs: ['oscuro', 'oscura', 'sombrio', 'lugubre', 'retorcido'],
    relatedConceptIds: ['dark_fantasy', 'dark_romance', 'gothic'],
  ),
];

/// Concepts offered as one-tap suggestions when the discovery query is empty.
const List<String> kSuggestedConceptIds = [
  'halloween',
  'cozy',
  'dark_academia',
  'fantasy_romance',
  'enemies_to_lovers',
  'space_opera',
];
